### ISSUE TITLE
Python CLI script on Windows - ConnectionResetError [WinError 10054]

### ISSUE THREAD

**Issue by rufik** [tomikaa87/gree-remote#62]
I'm trying to run gree.py on Windows 11 using python 3.10 but no luck, I'm getting `ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host` all the time, no matter what I do.
Anyone succeeded on windows?

```
$ .\python.exe C:\workspace\home-assistant\gree.py -b 192.168.55.255 search
Searching for devices using broadcast address: 192.168.55.255
Search finished, found 1 device(s)
Binding device: 192.168.55.18 (c6a4XXXX, ID: 502cc6aXXXXX)
Bind to 502cc6aXXXXX succeeded, key = Pq9St2Vw5YzXXXXX

$ .\python.exe C:\workspace\home-assistant\gree.py --verbose -c 192.168.55.32 -i 502cc6aXXXXX -k Pq9St2Vw5YzXXXXX get Pow
Getting parameters: Pow
send_data: ip=192.168.55.32, port=7000, data=b'{"cid":"app","i":0,"pack":"3LbLoQxLG6Ulufx/18NHB9khXFXA2SxQBCKZI3tL2+9iihDQaZQfQ3o42gZa95Z8MOIuRn73jYAffH44aaJ+dQ==","t":"pack","tcid":"502cc6aXXXXX","uid":0}'
Traceback (most recent call last):
  File "C:\workspace\home-assistant\gree.py", line 251, in <module>
    get_param()
  File "C:\workspace\home-assistant\gree.py", line 164, in get_param
    result = send_data(args.client, 7000, bytes(request, encoding='utf-8'))
  File "C:\workspace\home-assistant\gree.py", line 37, in send_data
    return s.recv(1024)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```
```
$ .\python.exe -V
Python 3.10.7

$ .\Scripts\pip.exe install pyopenssl
Requirement already satisfied: pyopenssl in c:\uses\python310\lib\site-packages (23.1.1)
Requirement already satisfied: cryptography<41,>=38.0.0 in c:\uses\python310\lib\site-packages (from pyopenssl) (38.0.1)
Requirement already satisfied: cffi>=1.12 in c:\uses\python310\lib\site-packages (from cryptography<41,>=38.0.0->pyopenssl) (1.15.1)
Requirement already satisfied: pycparser in c:\uses\python310\lib\site-packages (from cffi>=1.12->cryptography<41,>=38.0.0->pyopenssl) (2.21)
```

**Comment by tomikaa87** [comment]
Hi @rufik,

You're using the wrong device address. You AC was found at 192.168.55.18, but you're trying to send commands to 192.168.55.32.

**Comment by rufik** [comment]
Thank you, my understanding of `-c CLIENT   IP address of the client device` option was totally wrong! I clearly thought that "client" means my desktop (and "server" is AC).
